test with publish workflow

diff --git a/.github/workflows/runTestAndPublishTag.yml b/.github/workflows/runTestAndPublishTag.yml
--- a/.github/workflows/runTestAndPublishTag.yml
+++ b/.github/workflows/runTestAndPublishTag.yml
@@ -5,13 +5,21 @@ on:
     types: [published]
 
 jobs:
-  run-tests:
-    name: run-tests
+  publish-package:
     runs-on: ubuntu-latest
 
     steps:
       - name: Check out code
         uses: actions/checkout@v4
+
+      - name: Check tag format
+        run: |
+          TAG_NAME=${GITHUB_REF#refs/tags/}
+          if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Tag $TAG_NAME does not match the required format vX.Y.Z"
+            exit 1
+          fi
+          echo "Tag format is correct: $TAG_NAME"
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -24,38 +32,11 @@ jobs:
       - name: Run Jest tests
         run: npm test
 
-  publish-package:
-    name: publish-to-npm
-    needs: run-tests
-    runs-on: ubuntu-latest
-    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
-
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '22'
-
-      - name: Check tag format
-        run: |
-          TAG_NAME=${GITHUB_REF#refs/tags/}
-          if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Tag $TAG_NAME does not match the required format vX.Y.Z"
-            exit 1
-          fi
-          echo "Tag format is correct: $TAG_NAME"
-
       - name: Set version from Git tag
         run: |
           VERSION=$(echo ${GITHUB_REF#refs/tags/}) # Git-Tag extrahieren
           echo "Setting version to $VERSION"
           jq --arg VERSION "$VERSION" '.version = $VERSION' package.json > temp.json && mv temp.json package.json
-
-      - name: Install dependencies
-        run: npm install
 
       - name: Authenticate with npm
         run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
