test with publish workflow

diff --git a/.github/workflows/runTestAndPublishTag.yml b/.github/workflows/runTestAndPublishTag.yml
--- a/.github/workflows/runTestAndPublishTag.yml
+++ b/.github/workflows/runTestAndPublishTag.yml
@@ -1,9 +1,8 @@
 name: Test and Release on Tag
 
 on:
-  push:
-    tags:
-      - 'v[0-9]+.[0-9]+.[0-9]+'
+  release:
+    types: [published]
 
 jobs:
   run-tests:
@@ -39,6 +38,15 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: '22'
+
+      - name: Check tag format
+        run: |
+          TAG_NAME=${GITHUB_REF#refs/tags/}
+          if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Tag $TAG_NAME does not match the required format vX.Y.Z"
+            exit 1
+          fi
+          echo "Tag format is correct: $TAG_NAME"
 
       - name: Set version from Git tag
         run: |
